name: Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    name: Java ${{ matrix.java }}

    strategy:
      matrix:
        java:
          - '11' # EOL: 2023-09
          - '17' # EOL: 2026-09
          - '20' # EOL: 2023-09
         #- '21' # REL: 2023-09
         # see supported java release schedule at https://www.oracle.com/java/technologies/java-se-support-roadmap.html
    steps:
    - uses: actions/checkout@v3
      with:
        repository: getargv/getargv
        path: getargv
        token: ${{ secrets.GH_PAT }}
    - name: Build libgetargv
      run: make install_dylib
      working-directory: getargv
    - uses: actions/checkout@v3
      with:
        path: getargv.java
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
        check-latest: true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: getargv.java
    - name: Test with Maven
      run: mvn -B test --file pom.xml
      working-directory: getargv.java
